version: "3.8"

services:
  app:
    build: .
    container_name: meu_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ezfin
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: meu_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ezfin
    ports:
      - "5432:5432"